export const POST_TYPES = {
  CREATE_POST: "CREATE_POST",
  LOADING_POST: "LOADING_POST",
  GET_POSTS: "GET_POSTS",
  UPDATE_POST: "UPDATE_POST",
  GET_POST: "GET_POST",
  UPDATE_DETAIL_POST: "UPDATE_DETAIL_POST",
  DELETE_POST: "DELETE_POST",
  GET_RELATED_POSTS: "GET_RELATED_POSTS",
};
